### ISSUE TITLE
157 line bug

### ISSUE THREAD

**Issue by VBortsov** [howl0893/custom-object-detection-datasets#2]
To fix the bug, we changed "./python/coco_json_utils.py", line 157 to
contours = measure.find_contours(np.array(mask), 0.5, positive_orientation='low')

**Comment by smilerichpse** [comment]
thank you

**Comment by abstract-entity** [comment]
Big thanks, was not familliar with python u fix the script. Last stack error was for me:

"Image.py", line 546, in __getattr__ raise AttributeError(name)
AttributeError: shape
