### ISSUE TITLE
custom image 3d annotation to 3d kitti format 

### ISSUE THREAD

**Issue by akzenith** [howl0893/custom-object-detection-datasets#3]
I've annotated images using 3D BOUNDING BOXES. How can I convert to 3D KITTI DATASET format?

**Comment by howl0893** [comment]
Sorry for the delayed reply. I haven't worked on this in a long time. I would suggest finishing making the COCO dataset, then [convert to KITTI](https://www.youtube.com/watch?v=N6D9W-ytQc4)
